#amazon.dynamodb.endpoint=dynamodb.us-east-2.amazonaws.com
#amazon.aws.region=us-east-2
#amazon.aws.accesskey=key
#amazon.aws.secretkey=key2

aws:
  region: us-east-2
  accessKey: EMPTY
  secretKey: EMPTY
  dynamodb:
    endpoint: http://localhost:8000

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
